name: Super-Linter

on:
  push:
    branches:
      - main

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Super-Linter

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
